[package]
name = "missed-connections-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
tokio-postgres = "0.7.6"
serde_json = "1.0"

